with-expecter: true
resolve-type-alias: false # будет по умолчанию false в v3
disable-version-string: true # будет по умолчанию true в v3
issue-845-fix: true # требуется явно установить

packages:
  pkg/kafka:
    config:
      all: true
      dir: pkg/kafka/mocks
      outpkg: kafka
  pkg/kafka/franz-go-consumer:
    config:
      all: true
      dir: pkg/kafka/franz-go-consumer/mocks
      outpkg: franzgo
