brokers:
  - 'localhost:9092'
topic: 'orders'
group_id: 'order-producer'
batch_size: 1 # если за 5 сек не будет нужного количества собщений в батче - будет ошибка по таймауту
batch_timeout: 5s
min_bytes: 1
max_bytes: 10485760
max_wait: 1s
disable_auto_topic_creation: false

producer:
  enabled: true
  compression: 'snappy'
  required_acks: 'all'
  max_attempts: 3
  async: false
