// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with no fields
func (_m *MockConsumer) GetStats() (int64, int64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int64
	var r1 int64
	if rf, ok := ret.Get(0).(func() (int64, int64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// MockConsumer_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockConsumer_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) GetStats() *MockConsumer_GetStats_Call {
	return &MockConsumer_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockConsumer_GetStats_Call) Run(run func()) *MockConsumer_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_GetStats_Call) Return(processed int64, dlq int64) *MockConsumer_GetStats_Call {
	_c.Call.Return(processed, dlq)
	return _c
}

func (_c *MockConsumer_GetStats_Call) RunAndReturn(run func() (int64, int64)) *MockConsumer_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with no fields
func (_m *MockConsumer) Shutdown() {
	_m.Called()
}

// MockConsumer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockConsumer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Shutdown() *MockConsumer_Shutdown_Call {
	return &MockConsumer_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockConsumer_Shutdown_Call) Run(run func()) *MockConsumer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Shutdown_Call) Return() *MockConsumer_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_Shutdown_Call) RunAndReturn(run func()) *MockConsumer_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockConsumer) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsumer_Expecter) Start(ctx interface{}) *MockConsumer_Start_Call {
	return &MockConsumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockConsumer_Start_Call) Run(run func(ctx context.Context)) *MockConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConsumer_Start_Call) Return(_a0 error) *MockConsumer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Start_Call) RunAndReturn(run func(context.Context) error) *MockConsumer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
