// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	kafka "pkg/kafka"

	mock "github.com/stretchr/testify/mock"
)

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockProducer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Close() *MockProducer_Close_Call {
	return &MockProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducer_Close_Call) Run(run func()) *MockProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Close_Call) Return(_a0 error) *MockProducer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_Close_Call) RunAndReturn(run func() error) *MockProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockProducer) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProducer_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockProducer_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockProducer_Expecter) IsEnabled() *MockProducer_IsEnabled_Call {
	return &MockProducer_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockProducer_IsEnabled_Call) Run(run func()) *MockProducer_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_IsEnabled_Call) Return(_a0 bool) *MockProducer_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_IsEnabled_Call) RunAndReturn(run func() bool) *MockProducer_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, msg
func (_m *MockProducer) Send(ctx context.Context, msg *kafka.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *MockProducer_Expecter) Send(ctx interface{}, msg interface{}) *MockProducer_Send_Call {
	return &MockProducer_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *MockProducer_Send_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *MockProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kafka.Message))
	})
	return _c
}

func (_c *MockProducer_Send_Call) Return(_a0 error) *MockProducer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_Send_Call) RunAndReturn(run func(context.Context, *kafka.Message) error) *MockProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function with given fields: ctx, messages
func (_m *MockProducer) SendBatch(ctx context.Context, messages []*kafka.Message) error {
	ret := _m.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*kafka.Message) error); ok {
		r0 = rf(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockProducer_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []*kafka.Message
func (_e *MockProducer_Expecter) SendBatch(ctx interface{}, messages interface{}) *MockProducer_SendBatch_Call {
	return &MockProducer_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, messages)}
}

func (_c *MockProducer_SendBatch_Call) Run(run func(ctx context.Context, messages []*kafka.Message)) *MockProducer_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*kafka.Message))
	})
	return _c
}

func (_c *MockProducer_SendBatch_Call) Return(_a0 error) *MockProducer_SendBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_SendBatch_Call) RunAndReturn(run func(context.Context, []*kafka.Message) error) *MockProducer_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
