// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	kafka "pkg/kafka"

	mock "github.com/stretchr/testify/mock"
)

// MockDLQSender is an autogenerated mock type for the DLQSender type
type MockDLQSender struct {
	mock.Mock
}

type MockDLQSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQSender) EXPECT() *MockDLQSender_Expecter {
	return &MockDLQSender_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDLQSender) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDLQSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDLQSender_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDLQSender_Expecter) Close() *MockDLQSender_Close_Call {
	return &MockDLQSender_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDLQSender_Close_Call) Run(run func()) *MockDLQSender_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDLQSender_Close_Call) Return(_a0 error) *MockDLQSender_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDLQSender_Close_Call) RunAndReturn(run func() error) *MockDLQSender_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockDLQSender) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockDLQSender_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockDLQSender_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockDLQSender_Expecter) IsEnabled() *MockDLQSender_IsEnabled_Call {
	return &MockDLQSender_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockDLQSender_IsEnabled_Call) Run(run func()) *MockDLQSender_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDLQSender_IsEnabled_Call) Return(_a0 bool) *MockDLQSender_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDLQSender_IsEnabled_Call) RunAndReturn(run func() bool) *MockDLQSender_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, originalMsg, processingErr
func (_m *MockDLQSender) Send(ctx context.Context, originalMsg *kafka.Message, processingErr error) error {
	ret := _m.Called(ctx, originalMsg, processingErr)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kafka.Message, error) error); ok {
		r0 = rf(ctx, originalMsg, processingErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDLQSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDLQSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - originalMsg *kafka.Message
//   - processingErr error
func (_e *MockDLQSender_Expecter) Send(ctx interface{}, originalMsg interface{}, processingErr interface{}) *MockDLQSender_Send_Call {
	return &MockDLQSender_Send_Call{Call: _e.mock.On("Send", ctx, originalMsg, processingErr)}
}

func (_c *MockDLQSender_Send_Call) Run(run func(ctx context.Context, originalMsg *kafka.Message, processingErr error)) *MockDLQSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kafka.Message), args[2].(error))
	})
	return _c
}

func (_c *MockDLQSender_Send_Call) Return(_a0 error) *MockDLQSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDLQSender_Send_Call) RunAndReturn(run func(context.Context, *kafka.Message, error) error) *MockDLQSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDLQSender creates a new instance of MockDLQSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQSender {
	mock := &MockDLQSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
